version: '3.7'

services:
  elasticsearch:
    image: elasticsearch:7.17.20
    container_name: elasticsearch_lebedev
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    healthcheck:
      test: "exit 0"
    networks:
      - net

  kibana:
    container_name: kibana_lebedev
    image: kibana:7.17.20
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - net
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432
    healthcheck:
      test: "exit 0"
    networks:
      net:

  web:
    build: .
    ports:
      - "8000:8000"
    command: sh -c "python opendata_parser.py && python manage.py search_index --rebuild -f &&
      python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    depends_on:
      elasticsearch:
        condition: service_healthy
      db:
        condition: service_healthy
    networks:
      - net
volumes:
  elasticsearch-data:
    driver: local
  postgres_data:
networks:
  net: