# Generated by Django 5.0.4 on 2024-04-23 08:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HeritageLostObjects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_reg", models.DateField()),
                ("reg_number", models.IntegerField(blank=True, null=True)),
                ("name", models.CharField(blank=True, null=True)),
                ("classification", models.CharField(blank=True, null=True)),
                ("category", models.CharField(blank=True, null=True)),
                ("state", models.CharField(blank=True, null=True)),
                ("height", models.CharField(blank=True, null=True)),
                ("width", models.CharField(blank=True, null=True)),
                ("length", models.CharField(blank=True, null=True)),
                ("weight", models.CharField(blank=True, null=True)),
            ],
            options={
                "db_table": "heritage_lost_objects",
                "managed": False,
            },
        ),
    ]
