# Generated by Django 5.0.4 on 2024-04-23 08:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lost_objects", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="heritagelostobjects",
            options={"managed": False, "ordering": ["id"]},
        ),
    ]
