# Generated by Django 5.0.4 on 2024-04-23 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lost_objects", "0002_alter_heritagelostobjects_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="HeritageLostObject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_reg", models.DateField(verbose_name="Дата регистрации")),
                (
                    "reg_number",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Регистрационный номер"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        null=True,
                        verbose_name="Название культурной ценности",
                    ),
                ),
                (
                    "classification",
                    models.CharField(
                        blank=True,
                        null=True,
                        verbose_name="Классификация культурной ценности",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        null=True,
                        verbose_name="Категория культурной ценности",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        null=True,
                        verbose_name="Описание состояния сохранности",
                    ),
                ),
                (
                    "height",
                    models.CharField(blank=True, null=True, verbose_name="Высота"),
                ),
                (
                    "width",
                    models.CharField(blank=True, null=True, verbose_name="Ширина"),
                ),
                (
                    "length",
                    models.CharField(blank=True, null=True, verbose_name="Длина"),
                ),
                ("weight", models.CharField(blank=True, null=True, verbose_name="Вес")),
            ],
            options={
                "verbose_name": "Утраченная ценность",
                "verbose_name_plural": "Утраченные ценности",
                "db_table": "heritage_lost_objects",
                "ordering": ["id"],
                "managed": False,
            },
        ),
        migrations.DeleteModel(
            name="HeritageLostObjects",
        ),
    ]
